icons_format = "{icon} "  # spacing control to uncramp icons

[icons.overrides]
cpu = [
    "\uf2db"
]
memory_mem = ["\uf538"]

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
driver = "upower"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi, w:4) / $mem_total.eng(prefix:Mi) ($mem_used_percents.eng(w:4)) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$total "

# [[block]]
# block = "net"
# device = "enp0s31f6"
# interval = 5

[[block]]
block = "net"
device = "wlp0s20f3"
interval = 5

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "load"
interval = 1
format = "$icon  1min avg: $1m.eng(w:4)"

# apt install libsensors
[[block]]
block = "temperature"
interval = 10
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
chip = "*-isa-*"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[[block.click]]
button = "left"
cmd = "gsimplecal"
