theme = "modern"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
driver = "upower"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "net"
device = "enp0s31f6"
interval = 5

[[block]]
block = "net"
device = "wlp2s0"
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# apt install lm-sensors
[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
