theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
driver = "upower"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "net"
device = "enp0s31f6"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
