
[shell]
program = "/usr/bin/zsh"

[font]
size = 9.0

#[font.bold]
#family = "CaskaydiaCove Nerd Font Mono"

#[font.bold_italic]
#family = "CaskaydiaCove Nerd Font Mono"

#[font.italic]
#family = "CaskaydiaCove Nerd Font Mono"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window]
decorations = "none"
opacity = 0.85

[window.dimensions]
columns = 0
lines = 0

[colors]
transparent_background_colors = true
